import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {migrationFiles} from '../scripts/migration-files.mjs';

test('catalogue pages search across all records and preserve sales selectors and tenant boundaries',async()=>{
 const db=new PGlite({extensions:{pgcrypto}});
 try {
  await db.exec('create role anon;create role authenticated;create schema extensions;');
  for(const file of migrationFiles)await db.exec(await readFile(new URL('../supabase/'+file,import.meta.url),'utf8'));
  const call=async(name,...args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) value`,args)).rows[0].value;
  await db.exec("insert into owner_accounts(username,password_hash) values('owner',crypt('owner-password',gen_salt('bf')))");
  const owner=await call('login_user','owner','owner-password');
  const shop=await call('create_shop',owner.token,'Shop','Pune','shop','shop-password');
  await call('admin_update_shop',owner.token,shop.id,'Fashion Shop','Pune',true,'fashion-admin','clothing');
  const renamed=await call('login_user','fashion-admin','shop-password');
  assert.equal(renamed.shopId,shop.id);
  await call('create_shop',owner.token,'Other','Pune','other','other-password');
  const outsider=await call('login_user','other','other-password');
  await call('manage_shop_staff',owner.token,shop.id,'create',JSON.stringify({name:'Cashier',username:'cashier',password:'cashier-password',role:'cashier'}));
  const cashier=await call('login_user','cashier','cashier-password');
  const action=(name,data)=>call('retail_action',owner.token,shop.id,crypto.randomUUID(),name,JSON.stringify(data));
  for(let n=0;n<61;n++) {
   await action('product',{name:'Product '+String(n).padStart(3,'0'),price:20,cost:10,stock:n,reorder:2,unit:'pcs',barcode:'code'+n,style:n===60?'Needle%':'',size:n===60?'M':'',colour:n===60?'Navy':'',category:'General'});
   await action('contact',{name:'Customer '+String(n).padStart(3,'0'),kind:'customer',phone:'900000'+n});
  }
  await action('contact',{name:'Supplier',kind:'supplier'});
  const page=(view,offset=0,query='',low=false,token=owner.token)=>call('retail_workspace_scoped',token,shop.id,'2026-09-01','2026-09-30',view,0,offset,query,low);
  const first=await page('products'), second=await page('products',50);
  assert.equal(first.products.length,50);assert.equal(second.products.length,11);
  assert.equal(first.pageTotals.products,61);assert.equal(second.catalogOffset,50);
  assert.equal(new Set([...first.products,...second.products].map(p=>p.id)).size,61);
  assert.deepEqual((await page('products')).products.map(p=>p.id),first.products.map(p=>p.id));
  assert.equal((await page('products',0,' code60 ')).products[0].barcode,'code60');
  const clothingProduct=(await page('products',0,'%')).products[0];
  assert.equal(clothingProduct.size,'M');
  assert.equal(clothingProduct.colour,'Navy');
  assert.equal((await page('products',0,'%')).products.length,1);
  assert.equal((await page('products',0,'',true)).products.length,3);
  assert.equal((await page('products',0,'missing')).pageTotals.products,0);
  const contacts=await page('customers',50);
  assert.equal(contacts.contacts.length,11);assert.equal(contacts.pageTotals.contacts,61);
  assert.equal((await page('customers',0,'90000060')).contacts.length,1);
  assert.equal((await page('suppliers')).contacts.length,1);
  assert.equal((await page('suppliers',0,'',false,cashier.token)).contacts.length,0);
  assert.equal((await page('products',0,'',false,cashier.token)).products[0].cost,undefined);
  await assert.rejects(page('products',0,'',false,outsider.token),/Shop access/);
  await assert.rejects(page('products',-1),/Invalid catalogue/);
  await assert.rejects(page('products',0,'x'.repeat(201)),/Invalid catalogue/);
  assert.equal((await page('sell')).products.length,50);
  assert.equal((await page('sell')).contacts.length,62);
  const lookup=await call('retail_product_lookup',owner.token,shop.id,'code60',50);
  assert.equal(lookup.length,1);
  assert.equal(lookup[0].barcode,'code60');
  const exportPage=await call('retail_report_export_page',owner.token,shop.id,'2026-09-01','2026-09-30',0,50);
  assert.equal(exportPage.invoices.length,0);assert.equal(exportPage.hasMore,false);
  assert.equal((await call('retail_workspace_scoped',owner.token,shop.id,'2026-09-01','2026-09-30','products',0)).products.length,50);
  const soldProduct=first.products.find(p=>Number(p.stock)>=3);
  assert.ok(soldProduct);
  const soldDay=(await db.query("select (now() at time zone 'Asia/Kolkata')::date::text d")).rows[0].d;
  const sale=await action('checkout',{lines:[{id:soldProduct.id,qty:3,price:20,discount:0}],method:'cash',paid:60});
  const soldPage=await call('retail_workspace_scoped',owner.token,shop.id,soldDay,soldDay,'products',0,0,'',false);
  assert.equal(Number(soldPage.productSales[soldProduct.id].qty),3);
  assert.equal(Number(soldPage.productSales[soldProduct.id].revenue),60);
  const futurePage=await call('retail_workspace_scoped',owner.token,shop.id,'2027-01-01','2027-01-31','products',0,0,'',false);
  assert.equal(futurePage.productSales[soldProduct.id],undefined);
  await action('return',{id:sale.id,reason:'Customer returned full bill',method:'cash'});
  const returnedPage=await call('retail_workspace_scoped',owner.token,shop.id,soldDay,soldDay,'products',0,0,'',false);
  assert.equal(returnedPage.productSales[soldProduct.id],undefined);
  const workspaceAfterSettings=await action('settings',{gstin:'',address:'Pune',state:'Maharashtra 27'}).then(()=>page('settings'));
  assert.equal(workspaceAfterSettings.shop.settings.shopType,'clothing');
  assert.deepEqual(await call('retail_feature_flags',owner.token,shop.id),{});
  assert.deepEqual(await call('retail_feature_flag_set',owner.token,shop.id,'bulk_import',false),{bulk_import:false});
  assert.deepEqual(await call('retail_feature_flag_set',owner.token,shop.id,'bulk_import',true),{bulk_import:true});
  await db.query("insert into shops(name,area,username,password_hash) select 'Scale shop '||n,'Pune','scale-'||n,crypt('scale-password',gen_salt('bf')) from generate_series(1,120)n");
  await db.query("insert into items(shop_id,name,category,buying_price,default_selling_price,stock,reorder_level) select id,'Scale item','General',1,2,5,1 from shops where username in ('scale-1','scale-2','scale-3')");
  const ownerShops=await call('list_shops',owner.token);
  assert.equal(ownerShops.length,122);
  assert.equal(ownerShops.find(s=>s.username==='fashion-admin').shopType,'clothing');
  assert.equal(ownerShops.find(s=>s.username==='scale-1').itemCount,1);
  assert.equal(ownerShops.find(s=>s.username==='scale-4').itemCount,0);
  const ownerTotals=await call('owner_summary',owner.token);
  assert.equal(ownerTotals.shopCount,122);
  assert.ok(Number(ownerTotals.inventoryValue)>=15);
  await assert.rejects(call('retail_feature_flag_set',cashier.token,shop.id,'ocr_jobs',false),/Super admin/);
  await assert.rejects(call('retail_feature_flag_set',owner.token,shop.id,'unknown',true),/Unknown feature/);
  // The deployment runner replays migrations; ensure overload replacement stays safe.
  for(const file of migrationFiles)await db.exec(await readFile(new URL('../supabase/'+file,import.meta.url),'utf8'));
  assert.equal((await page('products')).pageTotals.products,61);
 } finally {await db.close();}
});
