import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {migrationFiles} from '../scripts/migration-files.mjs';

test('retail delivery skips, routes and cashier permissions use the complete migration chain',async()=>{
 const db=new PGlite({extensions:{pgcrypto}});
 try{
  await db.exec('create role anon;create role authenticated;create schema extensions;');
  for(const file of migrationFiles)await db.exec(await readFile(new URL('../supabase/'+file,import.meta.url),'utf8'));
  const call=async(name,...args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) value`,args)).rows[0].value;
  await db.exec("insert into owner_accounts(username,password_hash) values('owner',crypt('owner-password',gen_salt('bf')))");
  const owner=await call('login_user','owner','owner-password');
  const shop=await call('create_shop',owner.token,'Shop','Pune','shop','shop-password');
  await call('create_shop',owner.token,'Other','Pune','other','other-password');
  const manager=await call('login_user','shop','shop-password');
  const outsider=await call('login_user','other','other-password');
  await call('manage_shop_staff',owner.token,shop.id,'create',JSON.stringify({name:'Cashier',username:'cashier',password:'cashier-password',role:'cashier'}));
  const cashier=await call('login_user','cashier','cashier-password');
  const action=(token,name,data,id=crypto.randomUUID())=>call('retail_action',token,shop.id,id,name,JSON.stringify(data));
  const product=await action(manager.token,'product',{name:'Milk',category:'Dairy',price:20,cost:10,stock:20,reorder:1,unit:'pcs'});
  const customer=await action(manager.token,'contact',{name:'Customer',kind:'customer',address:'Market street'});
  const supplier=await action(manager.token,'contact',{name:'Supplier',kind:'supplier'});
  const day=(await db.query("select (now() at time zone 'Asia/Kolkata')::date::text d")).rows[0].d;
  const tomorrow=(await db.query("select ((now() at time zone 'Asia/Kolkata')::date+1)::text d")).rows[0].d;
  const monthly=await action(manager.token,'recurring',{name:'Month end',contactId:customer.id,cadence:'monthly',nextDate:'2027-01-31',lines:[{id:product.id,qty:1,price:20}]});
  assert.ok((await call('retail_delivery_list',manager.token,shop.id,'2027-02-28')).some(row=>row.id===monthly.id));
  assert.ok((await call('retail_delivery_list',manager.token,shop.id,'2027-03-28')).some(row=>row.id===monthly.id));
  assert.ok(!(await call('retail_delivery_list',manager.token,shop.id,'2027-03-31')).some(row=>row.id===monthly.id));
  const rec=await action(manager.token,'recurring',{name:'Milk round',contactId:customer.id,cadence:'daily',nextDate:day,lines:[{id:product.id,qty:1,price:20,discount:0}]});
  await assert.rejects(call('retail_delivery_settings',outsider.token,shop.id,rec.id,'Wrong',[]),/Shop access/);
  await assert.rejects(call('retail_delivery_settings',cashier.token,shop.id,rec.id,'Wrong',[]),/Manager/);
  await assert.rejects(call('retail_schedule',cashier.token,shop.id,rec.id,true),/Manager/);
  await assert.rejects(call('add_item',cashier.token,shop.id,'Forbidden','General',1,2,1,0),/Manager/);
  await assert.rejects(call('edit_item',cashier.token,product.id,'Forbidden','General',1,2,0),/Manager/);
  await assert.rejects(call('set_stock_checked',cashier.token,product.id,10,20),/Manager/);
  assert.match((await call('delete_item_confirmed',cashier.token,product.id,'cashier-password')).error,/Manager/);
  await assert.rejects(action(cashier.token,'contact',{name:'Forbidden',kind:'supplier'}),/Manager/);
  await assert.rejects(action(cashier.token,'settle',{contactId:supplier.id,amount:1,method:'cash'}),/Manager/);
  await call('retail_delivery_settings',manager.token,shop.id,rec.id,'Market road',[day,day]);
  assert.deepEqual(await call('retail_delivery_list',manager.token,shop.id,day),[]);
  const upcoming=await call('retail_delivery_list',manager.token,shop.id,tomorrow);
  assert.equal(upcoming.length,1);assert.equal(upcoming[0].route,'Market road');
  const id=crypto.randomUUID();
  const skip=await action(manager.token,'recurring_run',{id:rec.id},id);
  assert.equal(skip.skipped,true);assert.deepEqual(await action(manager.token,'recurring_run',{id:rec.id},id),skip);
  assert.equal((await db.query('select next_date::text from retail_recurring where id=$1',[rec.id])).rows[0].next_date,tomorrow);
  assert.equal((await db.query('select count(*)::int n from retail_invoices')).rows[0].n,0);
  assert.equal(Number((await db.query('select stock from items where id=$1',[product.id])).rows[0].stock),20);
  assert.equal(Number(await call('retail_balance',customer.id)),0);
  await action(manager.token,'recurring_toggle',{id:rec.id});
  assert.deepEqual(await call('retail_delivery_list',manager.token,shop.id,tomorrow),[]);
  const auto=await action(manager.token,'recurring',{name:'Auto skip',contactId:customer.id,cadence:'daily',nextDate:day,lines:[{id:product.id,qty:1,price:20}]});
  await call('retail_delivery_settings',manager.token,shop.id,auto.id,'East',[day]);
  await call('retail_schedule',manager.token,shop.id,auto.id,true);
  await call('retail_run_schedules');await call('retail_run_schedules');
  assert.equal((await db.query('select count(*)::int n from retail_invoices')).rows[0].n,0);
  // Permission restrictions must not break an ordinary cashier checkout.
  const bill=await action(cashier.token,'checkout',{lines:[{id:product.id,qty:1,price:20}],method:'cash',paid:20});
  assert.equal(Number(bill.total),20);
  const noCosts=value=>{
   if(Array.isArray(value))value.forEach(noCosts);
   else if(value&&typeof value==='object')for(const [key,v] of Object.entries(value)){
    assert.ok(!['cost','buying_price','buyingPrice'].includes(key),`Leaked ${key}`);noCosts(v);
   }
  };
  noCosts(bill);
  const cashWorkspace=await call('retail_workspace',cashier.token,shop.id,day,day);
  noCosts(cashWorkspace);
  assert.ok(cashWorkspace.contacts.every(c=>c.kind==='customer'));
  for(const key of ['purchases','expenses','registers','movements','recurring','legacy'])assert.deepEqual(cashWorkspace[key],[]);
  noCosts(await call('get_shop_dashboard',cashier.token,shop.id));
  await assert.rejects(call('retail_workspace_page',cashier.token,shop.id,day,day,'products',50,0),/Manager/);
  const retryKey=crypto.randomUUID(),retryBody={lines:[{id:product.id,qty:1,price:20}],method:'cash',paid:20};
  await db.exec('begin');
  const restrictedBill=await action(cashier.token,'checkout',retryBody,retryKey);
  noCosts(restrictedBill);noCosts(await action(cashier.token,'checkout',retryBody,retryKey));
  await db.exec('rollback');
  const managerWorkspace=await call('retail_workspace',manager.token,shop.id,day,day);
  assert.equal(Number(managerWorkspace.products[0].buying_price),10);
  assert.ok(managerWorkspace.contacts.some(c=>c.kind==='supplier'));
  // An unauthorized target must not consume another tenant's request budget.
  await assert.rejects(call('retail_request_limit',outsider.token,shop.id),/Shop access/);
  assert.equal((await call('retail_request_limit',manager.token,shop.id)).allowed,true);
  await db.query("update retail_request_windows set requests=600 where scope=$1",['shop:'+shop.id]);
  assert.equal((await call('retail_request_limit',cashier.token,shop.id)).allowed,false);
  assert.equal((await call('retail_request_limit',outsider.token,null)).allowed,true);
  await db.query("update retail_request_windows set window_start=now()-interval '2 minutes' where scope=$1",['shop:'+shop.id]);
  assert.equal((await call('retail_request_limit',cashier.token,shop.id)).allowed,true);
  await db.exec('begin');
  await db.query('insert into shop_quotas(shop_id,max_products) values($1,100)',[shop.id]);
  await db.query("insert into items(shop_id,name) select $1,'Quota item '||n from generate_series(1,99)n",[shop.id]);
  await db.exec('savepoint product_limit');
  await assert.rejects(action(manager.token,'product',{name:'Over limit',category:'General',price:1,cost:1,stock:1,reorder:0,unit:'pcs'}),/Product limit/);
  await db.exec('rollback to savepoint product_limit');
  assert.equal((await db.query('select count(*)::int n from items where shop_id=$1',[shop.id])).rows[0].n,100);
  await db.exec('rollback');
  const quoteAction=(token,name,details,id=crypto.randomUUID())=>call('retail_quote_action',token,shop.id,id,name,JSON.stringify(details));
  const quoteData={customerId:customer.id,validUntil:tomorrow,lines:[{id:product.id,qty:2,price:20,discount:10}]};
  await assert.rejects(quoteAction(cashier.token,'create',quoteData),/Manager/);
  const quoteKey=crypto.randomUUID();
  const quote=await quoteAction(manager.token,'create',quoteData,quoteKey);
  assert.equal(Number(quote.total),36);
  assert.deepEqual(await quoteAction(manager.token,'create',quoteData,quoteKey),quote);
  assert.equal(Number((await db.query('select stock from items where id=$1',[product.id])).rows[0].stock),19);
  await assert.rejects(quoteAction(outsider.token,'order',{id:quote.id}),/Shop access/);
  await assert.rejects(quoteAction(manager.token,'invoice',{id:quote.id,method:'cash',paid:36}),/transition/);
  await quoteAction(manager.token,'order',{id:quote.id});
  const invoiceKey=crypto.randomUUID();
  const converted=await quoteAction(manager.token,'invoice',{id:quote.id,method:'cash',paid:36},invoiceKey);
  assert.deepEqual(await quoteAction(manager.token,'invoice',{id:quote.id,method:'cash',paid:36},invoiceKey),converted);
  assert.equal(Number(converted.total),36);
  await assert.rejects(quoteAction(manager.token,'invoice',{id:quote.id,method:'cash',paid:36}),/transition/);
  assert.equal(Number((await db.query('select stock from items where id=$1',[product.id])).rows[0].stock),17);
  assert.equal((await call('retail_quote_list',manager.token,shop.id,0))[0].status,'invoiced');
  await db.exec('set role anon');
  await assert.rejects(db.query('select * from shop_staff'),/permission denied/);
 }finally{await db.close();}
});
