import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {parseCsv,csvText,lineTotal,report} from '../app/retail/domain.ts';

test('CSV import handles escaped quotes, multiline fields and malformed quotes',()=>{
 assert.deepEqual(parseCsv('name,category\r\n"Tea, green","A""B"\r\n"Two\nlines",G'),[['name','category'],['Tea, green','A"B'],['Two\nlines','G']]);
 assert.throws(()=>parseCsv('"unfinished'),/Unclosed/);
 assert.ok(csvText([['=evil','मराठी']]).includes("'=evil"));
 assert.equal(lineTotal({qty:1.5,price:20,discount:10}),27);
});
test('complete multi-shop retail transactions',async t=>{
 const db=new PGlite({extensions:{pgcrypto}});
 try{
 await db.exec('create role anon;create role authenticated;create schema extensions;');
 for(const name of ['schema.sql','inventory-operations.sql','migrations/20260912_retail_pos.sql'])await db.exec(await readFile(new URL('../supabase/'+name,import.meta.url),'utf8'));
 const call=async(name,args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
 const owner=(await db.query("insert into owner_accounts(username,password_hash) values('owner',crypt('owner-test-password',gen_salt('bf'))) returning id")).rows[0].id;
 assert.ok(owner);
 const superToken=(await call('login_user',['owner','owner-test-password'])).token;
 const a=await call('create_shop',[superToken,'Shop A','Pune','shopa','strong-password-a']);
 const b=await call('create_shop',[superToken,'Shop B','Mumbai','shopb','strong-password-b']);
 const shopLogin=await call('login_user',['shopa','strong-password-a']);
 let token=shopLogin.token;
 const other=(await call('login_user',['shopb','strong-password-b'])).token;
 const day=(await db.query("select (now() at time zone 'Asia/Kolkata')::date::text d")).rows[0].d;
 const act=(action,data={},id=crypto.randomUUID(),tok=token,shop=a.id)=>call('retail_action',[tok,shop,id,action,JSON.stringify(data)]);
 const workspace=(tok=token,shop=a.id)=>call('retail_workspace',[tok,shop,day,day]);
 let product,weighted,customer,supplier,invoice;
 const draft={name:'Tea',category:'Grocery',cost:8,price:10,stock:100,reorder:5,barcode:'123456',unit:'pcs',hsn:'0902',tax:0,expiry:''};
 await t.test('super admin creates two empty shops with separate usable credentials',async()=>{assert.equal((await call('list_shops',[superToken])).length,2);await assert.rejects(call('list_shops',[token]),/Super admin/);assert.equal(shopLogin.role,'shop');assert.equal(shopLogin.shopId,a.id);assert.equal((await workspace()).products.length,0);assert.equal((await workspace(other,b.id)).products.length,0);await assert.rejects(call('create_shop',[token,'X','Pune','x','strong-pass-xxx']),/Owner/);});
 await t.test('shop creates products and independent customer/supplier contacts',async()=>{product=await act('product',draft);weighted=await act('product',{...draft,name:'Rice',barcode:'',unit:'kg',stock:20.5});customer=await act('contact',{kind:'customer',name:'Customer A'});supplier=await act('contact',{kind:'supplier',name:'Supplier A'});assert.equal((await workspace()).products.length,2);});
 await t.test('every retail operation rejects cross-shop access and arbitrary identifiers',async()=>{await assert.rejects(workspace(other,a.id),/Shop access/);for(const action of ['checkout','product','contact','settle','purchase','expense','return','settings','register_open','recurring'])await assert.rejects(act(action,{},crypto.randomUUID(),other,a.id),/Shop access/);await assert.rejects(act('checkout',{lines:[{id:product.id,qty:1,price:10}],method:'cash'},crypto.randomUUID(),other,b.id),/Product does not belong/);await assert.rejects(call('admin_update_shop',[token,b.id,'Hacked','Pune',true]),/Super admin/);});
 await t.test('cash register and atomic multi-item checkout',async()=>{await act('register_open',{amount:100});invoice=await act('checkout',{lines:[{id:product.id,qty:2,price:10},{id:weighted.id,qty:1.5,price:20}],method:'cash'});assert.equal(invoice.total,50);const w=await workspace();assert.equal(w.products.find(p=>p.id===product.id).stock,98);assert.equal(w.products.find(p=>p.id===weighted.id).stock,19);assert.equal(w.registers[0].currentExpected,150);assert.equal(w.invoices.length,1);});
 await t.test('same checkout retry returns one invoice and rejects payload reuse',async()=>{const id=crypto.randomUUID(),payload={lines:[{id:product.id,qty:1,price:10}],method:'cash'};const i=await act('checkout',payload,id);assert.equal((await act('checkout',payload,id)).id,i.id);await assert.rejects(act('checkout',{...payload,method:'upi'},id),/different details/);assert.equal((await workspace()).invoices.length,2);});
 await t.test('failed cart rolls back all items; duplicates, fractional pieces and invalid payments rejected',async()=>{const before=await workspace();await assert.rejects(act('checkout',{lines:[{id:product.id,qty:1,price:10},{id:weighted.id,qty:1000,price:20}],method:'cash'}),/Insufficient/);assert.deepEqual((await workspace()).products,before.products);await assert.rejects(act('checkout',{lines:[{id:product.id,qty:1.5,price:10}],method:'cash'}),/whole/);await assert.rejects(act('checkout',{lines:[{id:product.id,qty:1,price:10},{id:product.id,qty:1,price:10}],method:'cash'}),/duplicate/);await assert.rejects(act('checkout',{lines:[{id:product.id,qty:1,price:10}],method:'cash',paid:5}),/customer/);await assert.rejects(act('checkout',{lines:[{id:product.id,qty:1,price:10}],method:'cash',paid:11}),/Payment/);});
 let credit;
 await t.test('customer partial payment, balance, and overpayment prevention',async()=>{credit=await act('checkout',{lines:[{id:product.id,qty:10,price:10}],method:'cash',paid:30,contactId:customer.id});assert.equal((await workspace()).contacts.find(c=>c.id===customer.id).balance,70);await act('settle',{contactId:customer.id,amount:20,method:'upi'});assert.equal((await workspace()).contacts.find(c=>c.id===customer.id).balance,50);await assert.rejects(act('settle',{contactId:customer.id,amount:51,method:'cash'}),/exceeds/);});
 await t.test('full return refunds collected money and clears customer debt once',async()=>{const r=await act('return',{id:credit.id,reason:'Customer returned all items',method:'cash'});assert.equal(r.refund,50);assert.equal((await workspace()).contacts.find(c=>c.id===customer.id).balance,0);await assert.rejects(act('return',{id:credit.id,reason:'Again',method:'cash'}),/already returned/);});
 await t.test('supplier purchase receives stock, records due and settles',async()=>{const stock=(await workspace()).products.find(p=>p.id===product.id).stock;const p=await act('purchase',{lines:[{id:product.id,qty:10,price:7}],contactId:supplier.id,reference:'SUP-1',paid:20,method:'cash'});assert.equal(p.total,70);let w=await workspace();assert.equal(w.products.find(p=>p.id===product.id).stock,stock+10);assert.equal(w.contacts.find(c=>c.id===supplier.id).balance,50);await act('settle',{contactId:supplier.id,amount:50,method:'cash'});assert.equal((await workspace()).contacts.find(c=>c.id===supplier.id).balance,0);});
 await t.test('cash close reconciles opening, collections, returns and expenses',async()=>{await act('expense',{description:'Delivery',amount:5,method:'cash'});const w=await workspace();const expected=100+50+10+30-50-20-50-5;assert.equal(w.registers[0].currentExpected,expected);const r=await act('register_close',{amount:expected+2});assert.equal(r.expected,expected);assert.equal(r.difference,2);await assert.rejects(act('register_close',{amount:0}),/Open a register/);});
 await t.test('GST inclusive pricing uses snapshots and reports reconcile',async()=>{await act('settings',{gstin:'27ABCDE1234F1Z5',address:'Pune Street',state:'Maharashtra 27'});const stock=(await workspace()).products.find(p=>p.id===product.id).stock;await act('product',{...draft,id:product.id,stock,expectedStock:stock,tax:18,price:118});const i=await act('checkout',{lines:[{id:product.id,qty:1,price:118}],method:'upi',interstate:true,supplyState:'Karnataka 29'});assert.equal(i.subtotal,100);assert.equal(i.tax,18);assert.equal(i.total,118);assert.equal(i.lines[0].hsn,'0902');const w=await workspace();const r=report(w);assert.equal(r.sales,178);assert.equal(r.tax,18);assert.equal(r.net,r.gross-5);});
 await t.test('stock edit checks stale quantities, duplicate barcode and expired products',async()=>{await assert.rejects(act('product',{...draft,id:product.id,expectedStock:-1}),/Stock changed/);await assert.rejects(act('product',draft),/duplicate key/);const expired=await act('product',{...draft,name:'Old milk',barcode:'old',expiry:'2020-01-01'});await assert.rejects(act('checkout',{lines:[{id:expired.id,qty:1,price:10}],method:'cash'}),/expired/);});
 await t.test('recurring billing advances due dates only once per occurrence',async()=>{const r=await act('recurring',{name:'Daily rice',contactId:customer.id,lines:[{id:weighted.id,qty:1,price:20}],cadence:'daily',nextDate:day});const i=await act('recurring_run',{id:r.id});assert.equal(i.total,20);assert.equal(i.paid,0);await assert.rejects(act('recurring_run',{id:r.id}),/No due/);await act('recurring_toggle',{id:r.id});assert.equal((await workspace()).recurring[0].active,false);});
 await t.test('paused shops lose sessions; super admin can reactivate and reset access',async()=>{await call('admin_update_shop',[superToken,a.id,'Shop A updated','Pune',false]);await assert.rejects(workspace(),/Shop access/);assert.equal((await workspace(superToken,a.id)).shop.active,false);await assert.rejects(act('expense',{amount:1,description:'X'},crypto.randomUUID(),superToken),/paused/);await call('admin_update_shop',[superToken,a.id,'Shop A','Pune',true]);token=(await call('login_user',['shopa','strong-password-a'])).token;assert.ok((await workspace()).products.length);await call('reset_shop_password',[superToken,a.id,'new-strong-pass-a']);await assert.rejects(workspace(),/Shop access/);await assert.rejects(call('login_user',['shopa','strong-password-a']),/Invalid/);token=(await call('login_user',['shopa','new-strong-pass-a'])).token;});
 await t.test('raw tables and internal balance helpers cannot be called anonymously',async()=>{await db.exec('set role anon');for(const table of ['retail_contacts','retail_invoices','retail_requests','retail_registers'])await assert.rejects(db.query(`select * from ${table}`),/permission denied/);await assert.rejects(db.query('select retail_balance($1)',[customer.id]),/permission denied/);await db.exec('reset role');});
 await t.test('migration reruns preserve shops, bills and credentials',async()=>{const before=await workspace();await db.exec(await readFile(new URL('../supabase/migrations/20260912_retail_pos.sql',import.meta.url),'utf8'));assert.equal((await workspace()).invoices.length,before.invoices.length);assert.equal((await workspace(other,b.id)).invoices.length,0);});
 }finally{await db.close();}
});
