export const inventoryCopy = {
  en: {
    inventory: 'Inventory', sales: 'Today’s Sales', closing: 'Daily Closing',
    todaySales: 'Today Sales', todayProfit: 'Today Profit', lowStock: 'Low Stock Items', products: 'Total Products',
    addSale: 'Add Sale', updateStock: 'Update Stock', addItem: 'Add Item', editItem: 'Edit Item',
    search: 'Search products', allCategories: 'All categories', allStock: 'All stock', in: 'In Stock', low: 'Low Stock', out: 'Out of Stock',
    name: 'Item Name', category: 'Category', stock: 'Available Qty', buy: 'Buy Price', sell: 'Sell Price', sold: 'Sold Today',
    revenue: 'Revenue', profit: 'Profit', status: 'Restock Status', actions: 'Actions', edit: 'Edit', remove: 'Delete',
    clear: 'Clear filters', noItems: 'No products yet', firstItem: 'Add your first shop item to start tracking stock and sales.',
    noMatch: 'No matching products', noSales: 'No sales recorded today',
    product: 'Product', choose: 'Choose a product', qty: 'Quantity sold', salePrice: 'Price per unit', threshold: 'Low-stock alert at',
    save: 'Save', saveSale: 'Save Sale', saving: 'Saving…', cancel: 'Cancel',
    invalid: 'Check the fields. Quantities must be whole numbers, and prices cannot be negative.',
    overStock: 'Not enough stock. Reduce the quantity or update stock first.',
    saved: 'Saved successfully.', failed: 'Could not save. Your entries are still here.',
    stale: 'Stock changed on another device. Refresh and enter the new count.',
    setup: 'The database update is required. Contact the store owner.',
    stockHint: 'Enter the total quantity you counted, not the quantity received.',
    deleteTitle: 'Delete this item?', deleteHint: 'The item will leave inventory. Past sales and profit records will be kept.',
    refresh: 'Refresh', refreshing: 'Refreshing…', refreshError: 'Could not refresh. The last loaded data is shown.',
    units: 'Units sold', transactions: 'Sales recorded', value: 'Stock value at cost', download: 'Download summary',
    closingHint: 'Today’s totals and current stock, in India Standard Time. Update physical counts before downloading.',
    results: 'products shown', restockHint: 'At or below the alert quantity', noRestock: 'No items need restocking.',
    retry: 'Try again', saleSearch: 'Find a product', available: 'Available', stockAction: 'Stock',
    uncertain: 'The sale may have saved. Try again here to check the same sale without charging stock twice.',
  },
  mr: {
    inventory: 'साठा', sales: 'आजची विक्री', closing: 'दैनिक हिशोब',
    todaySales: 'आजची विक्री', todayProfit: 'आजचा नफा', lowStock: 'कमी साठ्याचे आयटम', products: 'एकूण उत्पादने',
    addSale: 'विक्री नोंदवा', updateStock: 'साठा बदला', addItem: 'आयटम जोडा', editItem: 'आयटम बदला',
    search: 'उत्पादने शोधा', allCategories: 'सर्व प्रकार', allStock: 'सर्व साठा', in: 'साठा उपलब्ध', low: 'कमी साठा', out: 'साठा संपला',
    name: 'आयटमचे नाव', category: 'प्रकार', stock: 'उपलब्ध संख्या', buy: 'खरेदी किंमत', sell: 'विक्री किंमत', sold: 'आज विकले',
    revenue: 'विक्री रक्कम', profit: 'नफा', status: 'साठ्याची स्थिती', actions: 'कृती', edit: 'बदला', remove: 'काढून टाका',
    clear: 'फिल्टर काढा', noItems: 'अजून उत्पादने नाहीत', firstItem: 'साठा आणि विक्री नोंदवण्यासाठी पहिला आयटम जोडा.',
    noMatch: 'जुळणारी उत्पादने नाहीत', noSales: 'आज अजून विक्री नोंदवलेली नाही',
    product: 'उत्पादन', choose: 'उत्पादन निवडा', qty: 'विकलेली संख्या', salePrice: 'प्रति नग किंमत', threshold: 'कमी साठ्याची मर्यादा',
    save: 'जतन करा', saveSale: 'विक्री जतन करा', saving: 'जतन होत आहे…', cancel: 'रद्द करा',
    invalid: 'माहिती तपासा. संख्या पूर्णांक आणि किंमत शून्य किंवा अधिक असावी.',
    overStock: 'पुरेसा साठा नाही. संख्या कमी करा किंवा आधी साठा बदला.',
    saved: 'यशस्वीपणे जतन झाले.', failed: 'जतन झाले नाही. भरलेली माहिती कायम आहे.',
    stale: 'दुसऱ्या उपकरणावर साठा बदलला आहे. रीफ्रेश करून नवीन संख्या भरा.',
    setup: 'डेटाबेस अपडेट आवश्यक आहे. दुकानमालकाशी संपर्क करा.',
    stockHint: 'मोजलेली एकूण संख्या भरा, आलेल्या मालाची संख्या नाही.',
    deleteTitle: 'हा आयटम काढायचा?', deleteHint: 'आयटम साठ्यातून काढला जाईल. जुनी विक्री आणि नफ्याच्या नोंदी कायम राहतील.',
    refresh: 'रीफ्रेश', refreshing: 'रीफ्रेश होत आहे…', refreshError: 'रीफ्रेश झाले नाही. आधीची माहिती दिसत आहे.',
    units: 'विकलेले नग', transactions: 'विक्री नोंदी', value: 'खरेदी किमतीनुसार साठ्याचे मूल्य', download: 'हिशोब डाउनलोड करा',
    closingHint: 'भारतीय प्रमाणवेळेनुसार आजचा हिशोब आणि सध्याचा साठा. डाउनलोडपूर्वी प्रत्यक्ष मोजणीची संख्या भरा.',
    results: 'उत्पादने दिसत आहेत', restockHint: 'मर्यादेइतका किंवा त्यापेक्षा कमी साठा', noRestock: 'सर्व आयटमचा साठा पुरेसा आहे.',
    retry: 'पुन्हा प्रयत्न करा', saleSearch: 'उत्पादन शोधा', available: 'उपलब्ध', stockAction: 'साठा',
    uncertain: 'विक्री जतन झाली असू शकते. साठा पुन्हा कमी न करता तीच विक्री तपासण्यासाठी इथे पुन्हा प्रयत्न करा.',
  },
};
