import {readFile} from 'node:fs/promises';
import {loadEnvFile} from 'node:process';
import {databaseClient} from './database-client.mjs';
import {migrationFiles} from './migration-files.mjs';
import {createHash} from 'node:crypto';
try { loadEnvFile('.env.local'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is required');
const client=await databaseClient();
const files=[...migrationFiles,'retail-cron.sql'];
try{await client.connect();await client.query('begin');await client.query("set local lock_timeout='10s'; set local statement_timeout='60s'");let checksumReady=false;for(const file of files) { const source=await readFile(new URL('../supabase/'+file,import.meta.url),'utf8'); const checksum=createHash('sha256').update(source).digest('hex'); if(checksumReady){const old=await client.query('select checksum from schema_migrations where name=$1',[file]); if(old.rows[0]?.checksum && old.rows[0].checksum!==checksum) throw new Error(`Migration drift detected: ${file}`);} await client.query(source); if(file==='migrations/20261004_migration_checksums.sql') { checksumReady=true; for(const prior of files.slice(0,files.indexOf(file))) { const priorSource=await readFile(new URL('../supabase/'+prior,import.meta.url),'utf8'); await client.query('update schema_migrations set checksum=$2 where name=$1 and checksum is null',[prior,createHash('sha256').update(priorSource).digest('hex')]); } } if(checksumReady) await client.query('insert into schema_migrations(name,checksum) values($1,$2) on conflict(name) do update set checksum=coalesce(schema_migrations.checksum,excluded.checksum)',[file,checksum]); else await client.query('insert into schema_migrations(name) values($1) on conflict(name) do nothing',[file]); }await client.query("notify pgrst,'reload schema'");await client.query('commit');console.log('Retail migration and recurring scheduler applied. Existing shops and records preserved.');}catch(e){await client.query('rollback').catch(()=>{});console.error(e.message);process.exitCode=1;}finally{await client.end();}
